apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ns1
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: app2
    repoURL: https://github.com/Lesrac/argocd-apps.git
    targetRevision: {{ .Values.spec.source.targetRevision }}